[world]
name = "Nothing Game"
description = "A game where you should do nothing."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/0xAsten/nothing-game"
seed = "nothing_game"

[world.socials]
x = "https://x.com/0xAsten"
github = "https://github.com/0xAsten/nothing-game"

[namespace]
default = "nothing_game"

[env]
rpc_url = "http://localhost:5050/"
# Default account for katana with seed = 0
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"
world_address = "0x0456e4818b95a2fffc646f691e8df897952d2bb7e520232bdeeb26d91259ece9"

[writers]
"nothing_game" = ["nothing_game-character_system", "nothing_game-item_system", "nothing_game-shop_system"]
