[world]
name = "Nothing Game"
description = "A game where you should do nothing."
website = "https://github.com/0xAsten/nothing-game"
seed = "nothing_game"

[world.socials]
x = "https://x.com/0xAsten"
github = "https://github.com/0xAsten/nothing-game"

[namespace]
default = "nothing_game"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia "
account_address = ""
private_key = ""
world_address = "0x0456e4818b95a2fffc646f691e8df897952d2bb7e520232bdeeb26d91259ece9" 

[writers]
"nothing_game" = ["nothing_game-character_system", "nothing_game-item_system", "nothing_game-shop_system"]
